- correlation 
used for bivariate stats, looking at 2(numerical) columns from single observation(2 variables from single point)
measures the overlap between variables (how big is the overlap)
associated calculation 
demonstrate relationships between data

- Independant & Dependant variables
- - dependant 
    what you want to predict or explain
- - independant
    the variable that explains or predicts the outcome of the dependant variable 
Ex. age = independant
    wisdom = dependant 

- Pearson 'r' correlation
measures the strength and direction of teh linear relationships between two variables
ranges from -1 to 1
0 means no correlation 
1 means perfect positive correlation (as x increases y increases they move together)
-1 means perfect negative correlation(as x increase y decrease)
r sqaured = coefficient of determination 
cant have r without r squared (r**2) 

- Qualifications
- - must be continuous data
    not ranked, ordinal data, or categorial
- - must have linear relationship
    will not detect variability that expands or contracts at different point
- - Homoscedastic (equal variance)
    the variablilty of the dependant variable is the same at all levels of the independant variable 
    they move together 
skewness- indicates non linearity
kurt- indicate presence of outliears

- probability value
measures statistaical significance of the correlation, lower == better
p-value goes with r value
p-value <0.05 is typically considered significant 
p-value >0.05 is typically considered not significant
measures probability that future data will return 0.0

- 2 ways to calculate
- - scipy.stats.pearsonr(x,y) Ex. stats.pearsonr(df['x'],df['y'])
    includes p-value
- - df.corr(numeric_only=True)
    does not include p-value
    cheatcode to decide what calculations to check

In [1]:
import pandas as pd, scipy.stats as stats

url = 'https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/penguins_cleaned.csv'

df = pd.read_csv(url)
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      333.000000     333.000000         333.000000   333.000000
mean        43.992793      17.164865         200.966967  4207.057057
std          5.468668       1.969235          14.015765   805.215802
min         32.100000      13.100000         172.000000  2700.000000
25%         39.500000      15.600000         190.000000  3550.000000
50%         44.500000      17.300000         197.000000  4050.000000
75%         48.600000      18.700000         213.000000  4775.000000
max         59.600000      21.500000         231.000000  6300.000000

In [2]:
from classwork.evaluate_df import evaluate_df

edf = evaluate_df(df)
edf

,column_name,is_numeric,mean,median,min,max,Q25,Q75,std,num_null,num_unique,uniques<5
0,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.0,"[Adelie, Gentoo, Chinstrap]"
1,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.0,"[Torgersen, Biscoe, Dream]"
6,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2.0,"[male, female]"
2,NaN,True,43.992793,44.5,NaN,NaN,39.5,48.6,5.468668,0,NaN,NaN
3,NaN,True,17.164865,17.3,NaN,NaN,15.6,18.7,1.969235,0,NaN,NaN
4,NaN,True,200.966967,197.0,NaN,NaN,190.0,213.0,14.015765,0,NaN,NaN
5,NaN,True,4207.057057,4050.0,NaN,NaN,3550.0,4775.0,805.215802,0,NaN,NaN