In [2]:
import pandas as pd 
from scipy import stats

url = "https://raw.githubusercontent.com/nkmwicz/worldcup2018data/refs/heads/main/cleaned_events_world_cup2018.csv"

df = pd.read_csv(url)
df.head()

,eventId,subEventName,tags,playerId,matchId,eventName,teamId,matchPeriod,eventSec,subEventId,id,x1,y1,x2,y2
0,8,Simple pass,['Accurate'],Mohammad Ibrahim Al Sahlawi,"Russia - Saudi Arabia, 5 - 0",Pass,Saudi Arabia,1H,1.656214,Simple pass,258612104,50,50,35.0,53.0
1,8,High pass,['Accurate'],Abdullah Ibrahim Otayf,"Russia - Saudi Arabia, 5 - 0",Pass,Saudi Arabia,1H,4.487814,High pass,258612106,35,53,75.0,19.0
2,1,Air duel,"['Won', 'Accurate']",Ilya Kutepov,"Russia - Saudi Arabia, 5 - 0",Duel,Russia,1H,5.937411,Air duel,258612077,25,81,37.0,83.0
3,1,Air duel,"['Lost', 'Not accurate']",Yasir Gharsan Al Shahrani,"Russia - Saudi Arabia, 5 - 0",Duel,Saudi Arabia,1H,6.406961,Air duel,258612112,75,19,63.0,17.0
4,8,Simple pass,['Accurate'],Salman Mohammed Al Faraj,"Russia - Saudi Arabia, 5 - 0",Pass,Saudi Arabia,1H,8.562167,Simple pass,258612110,63,17,71.0,15.0

In [3]:
df.describe()

,eventId,eventSec,id,x1,y1,x2,y2
count,101759.000000,101759.000000,1.017590e+05,101759.000000,101759.000000,101755.000000,101755.000000
mean,5.749772,1388.637801,2.611401e+08,49.338191,49.843080,52.299641,49.712407
std,3.115089,850.980508,4.062610e+06,24.560054,30.012087,24.962312,30.356834
min,1.000000,0.122553,2.586121e+08,0.000000,0.000000,0.000000,0.000000
25%,1.000000,643.469486,2.593947e+08,31.000000,23.000000,33.000000,23.000000
50%,8.000000,1356.739817,2.603052e+08,48.000000,50.000000,55.000000,50.000000
75%,8.000000,2115.778718,2.610949e+08,68.000000,76.000000,71.000000,76.000000
max,10.000000,3258.366837,2.802175e+08,100.000000,101.000000,100.000000,101.000000

In [ ]:

df.info()
df["tags"] = df["tags"].apply(ast.literal_eval)

<class 'pandas.DataFrame'>
RangeIndex: 101759 entries, 0 to 101758
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   eventId       101759 non-null  int64
 1   subEventName  101587 non-null  str
 2   tags          101759 non-null  str
 3   playerId      101759 non-null  str
 4   matchId       101759 non-null  str
 5   eventName     101759 non-null  str
 6   teamId        101759 non-null  str
 7   matchPeriod   101759 non-null  str
 8   eventSec      101759 non-null  float64
 9   subEventId    101587 non-null  str
 10  id            101759 non-null  int64
 11  x1            101759 non-null  int64
 12  y1            101759 non-null  int64
 13  x2            101755 non-null  float64
 14  y2            101755 non-null  float64
dtypes: float64(3), int64(4), str(8)
memory usage: 11.6 MB